specVersion: 0.2.0
name: test-subql
version: 0.0.4
description: None.
repository: https://github.com/subquery/bifrost-subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: wss://bifrost-parachain.api.onfinality.io/public-ws
  genesisHash: '0x9f28c6a68e0fc9646eff64935684f6eeeece527e37bbe1f213d22caa1d9d6bed'
  dictionary: https://api.subquery.network/sq/subquery/bifrost-parachain-dictionary
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 380940
    mapping:
      file: ./dist/index.js
      handlers:
      # Salp and Salp-lite modules handlers
        - handler: handleSalpContributed
          kind: substrate/EventHandler
          filter:
            module: salp
            method: Contributed
        - handler: handleSalpLiteIssued
          kind: substrate/EventHandler
          filter:
            module: salpLite
            method: Issued
      # VstokenConversion module handlers
        - handler: handleVstokenConversionVsbondConvertToVsksm
          kind: substrate/EventHandler
          filter:
            module: vstokenConversion
            method: VsbondConvertToVsksm
        - handler: handleVstokenConversionVsksmConvertToVsbond
          kind: substrate/EventHandler
          filter:
            module: vstokenConversion
            method: VsksmConvertToVsbond
        - handler: handleVstokenConversionVsbondConvertToVsdot
          kind: substrate/EventHandler
          filter:
            module: vstokenConversion
            method: VsbondConvertToVsdot
        - handler: handleVstokenConversionVsdotConvertToVsbond
          kind: substrate/EventHandler
          filter:
            module: vstokenConversion
            method: VsdotConvertToVsbond
      # VsbondAuction module handlers
        - handler: handleVsbondAuctionOrderCreated
          kind: substrate/EventHandler
          filter:
            module: vsBondAuction
            method: OrderCreated
        - handler: handleVsbondAuctionOrderRevoked
          kind: substrate/EventHandler
          filter:
            module: vsBondAuction
            method: OrderRevoked
        - handler: handleVsbondAuctionOrderClinchd
          kind: substrate/EventHandler
          filter:
            module: vsBondAuction
            method: OrderClinchd
      # ZenlinkProtocol module handlers
        - handler: handleZenlinkProtocolAssetSwap
          kind: substrate/EventHandler
          filter:
            module: zenlinkProtocol
            method: AssetSwap
